# -*- coding: utf-8 -*-
"""tugas 1 kelompok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122-wiOtn3Tg52_G8i_qSRcueHCTzpNHj

**Nama Anggota:**


1.   Meylani Eka Sabila (2411012074)
2.   Maula Wulandari (2411012059)

1.   Hanifah Azhar (2411012051)
2.   Dwi Junita Putri (2411012062)

1.   Danu Galang Saputra (2451012016)
"""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "
data_baru = data_kotor.strip().replace("#", "")
data_pisah = data_baru.split("-")


list_skillhobi = data_pisah[3].split(",")
skillhobi_rapi = " & ".join(list_skillhobi).title()

id_panjang = len(data_pisah[0])
jumlah_skillhobi = len(list_skillhobi)

print("Data Mentah: '" ,data_kotor, "'")
print()
print("="*40)
print("      HASIL VERIFIKASI DATA")
print("="*40)
print("ID Pendaftar\t:", data_pisah[0],"(",id_panjang, "digit",")")
print("Nama Lengkap\t:", data_pisah[1].title())
print("Program Studi\t:",data_pisah[2].upper())
print("Skill Dikuasai\t:",skillhobi_rapi)
print("Total Skill\t:" ,jumlah_skillhobi)
print("Status Akun\t:" ,data_pisah[4].title())
print("="*40)